In [17]:
import numpy as np

In [18]:
a = np.array([1, 2, 3, 4, 5]) # одномерный массив из обычного списка
type(a) # отображение типа массива (обычный n-dimensional array)

numpy.ndarray

In [20]:
a.dtype # отображение типа элементов массива (int)

dtype('int64')

In [ ]:
a.shape # отображение формы массива (лишь одно число элементов, ведь массив одномерный)

(5,)

In [55]:
b = np.array([[1, 2, 3], [3, 4, 5]]) # двумерный массив
b

array([[1, 2, 3],
       [3, 4, 5]])

In [56]:
b.shape # форма двумерного массива

(2, 3)

In [24]:
zero=np.zeros((2, 3)) # двумерный массив с нулями
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
one=np.ones((2, 3)) # двумерный массив с единицами
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
c=np.arange(5, 15, 2) # создание массива с указанием начала, конца и шага (конец не включительно)
c

array([ 5,  7,  9, 11, 13])

In [ ]:
c[3] # получение третьего элемента массива (первый элемент считаем нулевым)

np.int64(11)

In [ ]:
c[1:4] # срез с первого по четвертый элемент не включительно

array([ 7,  9, 11])

In [33]:
c[[1,4]] # срез с выбором первого и четвертого элементов

array([ 7, 13])

In [ ]:
sum = a+c # поэлементное сложение (только для массивов одинаковой формы)
sum

array([ 6,  9, 12, 15, 18])

In [ ]:
mul = a*c # поэлементное умножение
mul

array([ 5, 14, 27, 44, 65])

In [ ]:
power = c**a # возведение в степень
power

array([     5,     49,    729,  14641, 371293])

In [ ]:
remain = c%a # остаток от деления
remain

array([0, 1, 0, 3, 3])

In [ ]:
a + 1 # сложение со скаляром

array([2, 3, 4, 5, 6])

In [ ]:
a * 2 # умножение на скаляр

array([ 2,  4,  6,  8, 10])

In [ ]:
c.min(), c.max() # минимум и максимум из массива c

(np.int64(5), np.int64(13))

In [57]:
b.mean() # средняя величина всего массива

np.float64(3.0)

In [58]:
b.mean(axis=0) # средняя величина по столбцам

array([2., 3., 4.])

In [59]:
b.mean(axis=1) # средняя величина по строкам

array([2., 4.])